# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    verify-gradle-wrapper:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: gradle/wrapper-validation-action@v1.0.3

    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                jdk: [11, 15]
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/cache@v2.1.4
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.jdk }}
            - run: ./gradlew build --stacktrace --warning-mode all

    release:
        runs-on: ubuntu-latest
        needs: [build, verify-gradle-wrapper] # build job must pass before we can release

        if: github.event_name == 'push'
            && github.ref == 'refs/heads/main'
            && github.repository == 'MinimallyCorrect/Mixin'
            && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
            && !contains(toJSON(github.event.commits.*.message), '[skip release]')

        steps:
            - name: Check out code
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci

            - uses: actions/cache@v2.1.4
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: releasing-${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}

            - name: Set up Java 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Build and publish to github
              run: ./gradlew -P releasing build publish githubRelease -s
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  DEPLOYMENT_REPO_URL_RELEASE: ${{secrets.DEPLOYMENT_REPO_URL_RELEASE}}
                  DEPLOYMENT_REPO_URL_SNAPSHOT: ${{secrets.DEPLOYMENT_REPO_URL_SNAPSHOT}}
                  DEPLOYMENT_REPO_USERNAME: ${{secrets.DEPLOYMENT_REPO_USERNAME}}
                  DEPLOYMENT_REPO_PASSWORD: ${{secrets.DEPLOYMENT_REPO_PASSWORD}}
